

#include "sdmllvm.hpp"


namespace profile_simple
{
    
    extern int stack_profiling_only(std::string InputFilename, std::string OutputFilename,int job ,bool Convert_object_file ) ;
    extern int heap_profiling_only (std::string InputFilename, std::string OutputFilename,int job, bool Convert_object_file);
    extern int GV_profiling_only(std::string InputFilename,std::string OutputFilename,int job, bool Convert_object_file);
    extern int  printResultFile(std::string InputFilename ,int job);
    extern int All_profiling(std::string InputFilename,std::string OutputFilename, int job,bool Convert_object_file);
    
}

#define help___ "\
USAGE:  \"./profiletool filename.bc  \n\
        \"./profiletool -a n -i filename.bc -o filename.o [-obj]\"  \n\
options:  \n\
    -a      action  \n\
            -a=1  Heap variable profiling only (heap variables allocated with malloc)  \n\
            -a=2  Stack variable profiling only  \n\
            -a=3  Global variable only  \n\
            -a=4  All memory regions (Heap,Stack,Global)  \n\
            \
    -i      input filename  \n\
    -o      output filename  \n\
    -obj    convert output bitcode to object file  \n\
  \n\
Eg 1:  \n\
    modify your application to profile all memory region  \n\
    $ ./profiletool swaption.bc  \n\
  \n\
    compile the output file in previous command to executable  \n\
    $ g++ swaption.o -o swaption  \n\
  \n\
    execute the modified application  \n\
    $ ./swaption \n\
  \n\
    the results files \"result.tpl\" and \"result.csv\" will the generated by the application  \n\
  \n\
Eg 2:  \n\
    modify your application to profile heap memory region  \n\
    $ ./profiletool -a=1 -i swaption.bc -o swaption.o -obj   \n\
  \n\
    compile the output file in previous command to executable  \n\
    $ g++ swaption.o -o swaption  \n\
  \n\
    execute the modified application  \n\
    $ ./swaption \n\
  \n\
    the results files \"result.tpl\" and \"result.csv\" will the generated by the application "


 